CREATE TABLE persons (
	Id INT(10) NULL DEFAULT NULL,
	FirstName VARCHAR(50) NULL DEFAULT NULL,
	LastName VARCHAR(50) NULL DEFAULT NULL,
	Adress VARCHAR(50) NULL DEFAULT NULL,
	Gender VARCHAR(50) NULL DEFAULT NULL		
);